language: python
python:
  - "3.8"
install:
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  - export CHEMCHECK=$(pwd)
  - echo $CHEMCHECK
  - export PYTHONPATH=$PATHONPATH:$CHEMCHECK
  - cd ChemCheck
  - conda env create -f environment.yml
  - source activate chemcheck_env
script:
  - cd ChemCheck
  - python manage.py makemigrations
  - python manage.py migrate
