language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - python -VV
  - pip freeze
  - git clone https://github.com/Cantera/cantera.git
  - cd cantera
  - echo "boost_inc_dir = '/opt/local/include'" >> config.log
  - scons build
  - scons install
script:
  - cd ChemCheck
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
