language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - python -VV
  - pip freeze
script:
  - cd ChemCheck
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
