# Generated by Django 2.2 on 2019-06-01 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemkin',
            name='timstamps',
        ),
        migrations.AddField(
            model_name='chemkin',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
