# Generated by Django 2.2.2 on 2019-06-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190601_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemkin',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='chemkin',
            name='mechanism_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chemkin',
            name='surface_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chemkin',
            name='thermo_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chemkin',
            name='transport_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
