# Generated by Django 2.2.1 on 2019-06-19 14:34

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20190611_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chemkin mechanism file', models.FileField(blank=True, null=True, upload_to=upload.models.upload_to)),
                ('Chemkin thermo file', models.FileField(blank=True, null=True, upload_to=upload.models.upload_to)),
                ('Chemkin transport file', models.FileField(blank=True, null=True, upload_to=upload.models.upload_to)),
                ('Chemkin surface file', models.FileField(blank=True, null=True, upload_to=upload.models.upload_to)),
                ('ct_mechanism_file', models.FileField(blank=True, null=True, upload_to=upload.models.upload_to, verbose_name='Cantera yaml file')),
                ('ct_conversion_errors', models.TextField(verbose_name='Errors from the ck2yaml conversion')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chemkin',
        ),
    ]
