# Generated by Django 2.2.1 on 2019-06-19 14:39

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20190619_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanism',
            name='Chemkin mechanism file',
        ),
        migrations.RemoveField(
            model_name='mechanism',
            name='Chemkin surface file',
        ),
        migrations.RemoveField(
            model_name='mechanism',
            name='Chemkin thermo file',
        ),
        migrations.RemoveField(
            model_name='mechanism',
            name='Chemkin transport file',
        ),
        migrations.AddField(
            model_name='mechanism',
            name='ck_mechanism_file',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.upload_to, verbose_name='Chemkin mechanism file'),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='ck_surface_file',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.upload_to, verbose_name='Chemkin surface file'),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='ck_thermo_file',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.upload_to, verbose_name='Chemkin thermo file'),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='ck_transport_file',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.upload_to, verbose_name='Chemkin transport file'),
        ),
    ]
