# Generated by Django 3.0.3 on 2020-02-28 15:53

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20190619_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discontinuous_species', models.ImageField(upload_to=upload.models.upload_to, verbose_name='discontinuous_species_images')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Mechanism')),
            ],
        ),
    ]
