# Generated by Django 3.0.3 on 2020-02-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
