# Generated by Django 3.0.3 on 2020-04-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanism',
            name='temperature',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
