# Generated by Django 3.0.3 on 2020-05-02 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20200424_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='temperature',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
