# Generated by Django 3.0.3 on 2020-05-02 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20200502_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='pressure',
            field=models.FloatField(blank=True, default=100000.0, null=True),
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='temperature',
            field=models.FloatField(blank=True, default=298, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
