# Generated by Django 3.0.3 on 2020-06-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20200502_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanism',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='mechanism',
            name='temperature',
        ),
    ]
