# Generated by Django 3.0.3 on 2020-06-11 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20200611_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='pressure',
            field=models.FloatField(blank=True, default=100000.0, null=True),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='temperature',
            field=models.FloatField(blank=True, default=298, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
