# Generated by Django 3.0.3 on 2020-06-11 05:21

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0017_auto_20200611_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(upload.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
