# Generated by Django 2.2.2 on 2019-06-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190605_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemkin',
            name='mechanism_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y%m%d-%H%M%S/chem.inp'),
        ),
        migrations.AlterField(
            model_name='chemkin',
            name='surface_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y%m%d-%H%M%S/surf.inp'),
        ),
        migrations.AlterField(
            model_name='chemkin',
            name='thermo_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y%m%d-%H%M%S/therm.dat'),
        ),
        migrations.AlterField(
            model_name='chemkin',
            name='transport_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y%m%d-%H%M%S/tran.dat'),
        ),
    ]
