name: Python application
on: [push]
jobs:
  build:
    name: Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: chemcheck_env
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
    
    - run: |
        conda info
        conda list

    - name: Make migrations
      run: python ChemCheck/manage.py makemigrations
    - name: Run migrations
      run: python ChemCheck/manage.py migrate
    - name: Run tests
      run: |
        cd ChemCheck
        python manage.py test
